# Generated by Django 5.0.3 on 2024-05-19 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_alter_student_group_student_promo_student_year_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='valid_group',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
