# Generated by Django 5.0.3 on 2024-06-04 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_student_valid_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='valid_group',
        ),
    ]
