# Generated by Django 5.0.3 on 2024-05-18 19:39

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0002_rename_school_years_teacher_classes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='courses',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=255, null=True), blank=True, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='position',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
